spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fwitterdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

